#  Tema 2 

Termen de predare: 19 octombrie 2023, ora 21:00. Numele fisierului va avea structura: laborator2_tema2_nume_prenume.ipynb.

## Precizări

1. Se vor folosi **type annotations** pentru variabile, parametri tuturor funcțiilor, tipuri de retur. Se vor folosi **docstrings** pentru toate funcțiile. Neîndeplinirea acestei cerințe duce la înjumătățirea punctajului pentru exercițiul în cauză. 
1. Înainte de a trimite tema, verificați acoperirea cerințelor. Notarea notebookului se va face prin rularea succesiva a celulelor, pana la prima blocare.
1. Se acorda doua puncte din oficiu.

## Conținut

1. Exercitii cu functii
1. Exercitii cu NumPy

## Execiții cu funcții:


 (1p) 1. Să se scrie o funcție care primește ca parametru un număr. Să se returneze lista cu toate prefixele numarului care sunt numere prime. 
 Exemplu: n=23510 -> [2, 23, 2351] 
 
 Puteti folosi functii auxuliare scrise de voi. 

In [1]:
def numar_prim(numar:int)->bool:
    '''
    Verifica daca un numar este prim
    :param numar(int): un numar intreg
    Returneaza un boolean 
    '''
    for i in range(2,numar):
        if (numar%i) == 0:
            return False
    return True 

def prefixele_prime(numar:str)->list[int]:
    '''
    Formeaza toate prefixele unui numar si le verifica daca sunt numere prime si le adauga intr-o lista.
    :param numar(string): sirul dat ca parametru
    Returneaza o lista de numnere intregi ce reprezinta prefixe care sunt numere prime
    '''
    lista_prefixe_prime:list=[]
    prefix:str=''
    for p in range(0,len(numar)):
        prefix += numar[p];
        if numar_prim(int(prefix)):
            lista_prefixe_prime.append(int(prefix))
    return lista_prefixe_prime

prefixele_prime('23510')

[2, 23, 2351]

(1p) 2. Scrieți o funcție care primește ca parametru o frază și care returnează un tuplu ce conține doar cuvintele palindroame. Un palindrom este un șir de caractere care citit de la dreapta la stânga are același continut ca si citirea de la stanga la dreapta. Separatorii de cuvinte sunt: ' ', ',', ':', ';'. E posibil sa fie mai multi separatori succesivi, de exemplu virgula urmata de spatiu.  

In [2]:
import re

def palindroame(fraza:str)->tuple[str]:
    '''
    Functia separa o fraza in cuvinte si verifica daca sunt palindroame, atunci cuvintele se adauga intr-o lista de palindroame
    :param fraza(string): o fraza data ca parametru, cu separatori de cuvinte ' ', ',', ':', ';'
    Returneaza un tuplu de stringuri ce sunt palindroame
    '''
    lista_cuvinte:list = re.split(r'[ ,:;]+',fraza)
    lista_palindroame:list=[]
    for cuvant in lista_cuvinte:
        if cuvant==''.join(reversed(cuvant)):
            lista_palindroame.append(cuvant)
    return tuple(lista_palindroame)

palindroame('ana, are: mere, ene')

('ana', 'ene')

(0.5p) 3. Definiți o funcție care primește ca parametru o propoziție (string sau listă). Să se returneze un tuplu ce indică numărul de consoane, numărul de vocale și numărul de cifre din parametrul primit. Includeti in tuplu o valoare booleana cara arata daca suma celor 3 valori formează un pătrat perfect.

In [3]:
import math

def functie3(propozitie:str)->tuple[int,int,int,bool]: 
    '''
    Functia calculeaza numarul de consoane, numarul de vocale și numarul de cifre;
    se verifica daca radical din suma numerelor de litere si numerelor de cifre este un numar intreg pentru verifica daca reprezinta un patrat perfect
    :param propozitie(string): o propozitie data
    Returneaza un tuplu cu numarul de consoane, numarul de vocale, numarul de cifre și dacă suma lor formează un pătrat perfect
    
    '''
    consoane:str='bcdfghjklmnpqrstvwxyzBCDFGHJKLMNPQRSTVWXYZ'
    vocale:str='aeiouAEIOU'
    cifre:str='1234567890'
    nr_consoane:int=0
    nr_vocale:int=0
    nr_cifre:int=0
    patrat_perfect:bool=False
    for caracter in propozitie:
        if caracter in consoane:
            nr_consoane+=1
        elif caracter in vocale:
            nr_vocale+=1
        elif caracter in cifre:
            nr_cifre+=1
    patrat_perfect= math.sqrt(nr_consoane+nr_vocale+nr_cifre).is_integer()        
    return (nr_consoane,nr_vocale,nr_cifre,patrat_perfect)

functie3('Ana are 7435 de mere.')

(5, 7, 4, True)

(1p) 4. Se da un vector cu numere intregi nenule. Sa se determine toti indicii `i` unde urmeaza o schimbare de semn. Codul se va scrie intr-o functie adnotata.

Exemplu: 
```python
v = [1, 2, -1, 2, 3, -1, 3, -10, -10, -10]
```
Trebuie sa rezulte vectorul de indici: `[1, 2, 4, 5, 6]`.

De luat in considerare ca:
1. Magnitudinea valorilor nu conteaza, doar semnele lor
1. Functia `where` gaseste indicii unde anumite proprietati sunt indeplinite

Implementarea furnizata trebuie sa fie diferita fata de cea naiva de mai jos.

In [4]:
import numpy as np

def jumping(v:list[int])->list[int]: 
    '''
    Se determină toti indicii elementelor din vectorul dat unde urmeaza o schimbare de semn,
    :param v(list[int]): vector de numere intregi
    Returneaza list[int], indicii elementelor unde urmeaza o schimbare de semn in vector
    ''' 
    assert np.all( v != 0), 'All values should be non-zero'
    return np.where(np.diff(np.sign(v)) != 0)[0]

# test 1
v = np.array([1, 2, -1, 2, 3, -1, 3, -10, -10, -10])
print(jumping(v))
assert np.all(jumping(v) == [1, 2, 4, 5, 6])

# test 2: random vector, naive counting
v = np.random.randint(-100, 100, 1000)
# patching 0 values
v[v==0] = -1
# naive way of counting jumps:
positions = []
for i in range(len(v)-1):
    if v[i] * v[i+1] < 0:
        positions.append(i)
    
assert np.all(positions == jumping(v))

[1 2 4 5 6]


## Probleme NumPy

(0.5 p) 5. Se dă un vector NumPy de valori numerice. Să se determine lista elementelor care au mai mult de o aparitie.  

In [5]:
'''
Se da vectorul a de valori numerice
Se determina lista elementelor care au mai mult de o aparitie
'''
a = np.array([1, 4, 2, 5, 2, 3, 3, 4])
numbers, counts=np.unique(a,return_counts=True)
print(numbers[counts>1])

[2 3 4]


(0.5p) 6. Pentru o matrice de numere să se determine suma dintre minimul si maximul elementelor de pe linii sau de pe coloane, în funcție de valoarea unui parametru de tip boolean `compute_on_columns`.

In [6]:
def sume(mat:np.ndarray, compute_on_columns:bool)->list[int]:
    '''
    Functia determina suma dintre minimul si maximul elementelor de pe linii sau de pe coloan,
    in functie de valaoarea parametrului boolean
    :param mat(np.ndarray): matrice de numere
    :param compute_on_columns(bool): variabila care indica daca cautarea maximului si a minimului sa se faca pe coloane sau linii
    Returneaza o lista de int-uri.
    '''
    if(compute_on_columns):
        lista_min:list=np.min(mat,axis=0)
        lista_max:list=np.max(mat,axis=0)
        return lista_min+lista_max
    else:
        lista_min:list=np.min(mat,axis=1)
        lista_max:list=np.max(mat,axis=1)
        return lista_min+lista_max
    
mat=np.array([[1, 2, 3], 
              [9, 8, 7], 
              [6, 5, 4]])
print(sume(mat, True))
print(sume(mat, False))

[10 10 10]
[ 4 16 10]


(0.5p) 7. Pentru un număr `n` introdus de la tastaură, generați o matrice pătratică de `n*n` cu elemente aleatorii din intervalul `[0,2n]`. Calculați minimul elementelor de pe 
diagonala principală a matricei și maximul elementelor de pe diagonala secundară a matricei, folosind functii NumPy si cod vectorizat. Returnați rezultatele sub forma de tuplu.

In [7]:
def min_max_diagonale()->tuple[float,float]:
    '''
    Numărul n este introdus de la tastaură, 
    se genereaza o matrice pătratică de n*n cu elemente aleatorii din intervalul [0,2n]. 
    Se calculeaza minimul elementelor de pe diagonala principală a matricei și maximul elementelor de pe diagonala secundară a matricei.
    Returneaza un tuplu de minimul elementelor de pe diagonala principală si maximul elementelor de pe diagonala secundară
    '''
    n:int = int(input("Enter a number: "))
    mat = (np.random.rand(n*n)*2*n).reshape(n, n)
    minim=np.min(mat.diagonal())
    maxim=np.max(np.rot90(mat).diagonal())
    print(mat)
    return tuple([minim, maxim])

min_max_diagonale()

Enter a number: 5
[[8.58955878 2.280647   8.87172231 2.56931199 1.24047478]
 [1.20202656 0.89989863 8.15573133 1.56481248 6.95063149]
 [4.62695422 8.77407795 9.72818556 3.12002727 9.80444518]
 [9.71238668 4.53639165 2.44109925 6.14495748 8.07451898]
 [5.08414677 9.23099885 8.72773216 1.97573213 3.29421435]]


(0.8998986251223862, 9.728185555690281)

(1p) 8. Descarcați setul de date Wine descris la 'http://archive.ics.uci.edu/ml/datasets/Wine', fișierul `wine.data`, și încărcați-l într-o matrice NumPy, 
folosind `np.genfromtxt`. Alegeți aleator `n` poziții din cadrul matricei de valori, setați pe aceste pozitii `NaN`.  Construiți o funcție care, 
primind la intrare o matrice, returnează o colecție cu indicii de linii respectiv de coloane în care se găsesc valori `NaN`, precum si matricea 'corectată':  valorile `NaN` se umplu cu o valoare ca parametru al funcției. 

In [8]:
fname='wine.data'
mat=np.genfromtxt(fname,delimiter=',',dtype=float)
print('Matricea initiala:\n',mat)
n:int = int(input("\nEnter a number: "))
mat.ravel()[np.random.choice(mat.size, n, replace=False)] = np.nan
print('\nMatricea dupa inlocuirile cu NaN:\n',mat)

def inlocuire_nan(mat:np.ndarray,x:float)->tuple[np.ndarray,np.ndarray]:
    '''
    Functia gaseste indicii(coordonatele) elementelor NaN si le inlocuiesc cu valoarea parametrului x
    :param mat(np.ndarray): matrice de numere float
    :param x(float): o valoare float
    Returnează o colecție cu indicii de linii respectiv de coloane în care se găsesc valori NaN, 
    precum si matricea 'corectată': valorile NaN se umplu cu valoarea data ca parametru al funcției.
    '''
    indici = np.argwhere(np.isnan(mat))
    print('\nIndicii:\n',indici)
    mat2=np.nan_to_num(mat,nan=x)
    print('\nMatricea noua:\n',mat2)
    return tuple([indici,mat2])

rezultat = inlocuire_nan(mat,42)
print('\nIndici:\n',rezultat[0],'\nMatricea noua:\n',rezultat[1])

Matricea initiala:
 [[1.000e+00 1.423e+01 1.710e+00 ... 1.040e+00 3.920e+00 1.065e+03]
 [1.000e+00 1.320e+01 1.780e+00 ... 1.050e+00 3.400e+00 1.050e+03]
 [1.000e+00 1.316e+01 2.360e+00 ... 1.030e+00 3.170e+00 1.185e+03]
 ...
 [3.000e+00 1.327e+01 4.280e+00 ... 5.900e-01 1.560e+00 8.350e+02]
 [3.000e+00 1.317e+01 2.590e+00 ... 6.000e-01 1.620e+00 8.400e+02]
 [3.000e+00 1.413e+01 4.100e+00 ... 6.100e-01 1.600e+00 5.600e+02]]

Enter a number: 2100

Matricea dupa inlocuirile cu NaN:
 [[ nan  nan  nan ...  nan  nan  nan]
 [ nan  nan  nan ... 1.05  nan  nan]
 [1.    nan  nan ...  nan 3.17  nan]
 ...
 [ nan  nan  nan ...  nan 1.56  nan]
 [ nan  nan 2.59 ...  nan  nan  nan]
 [ nan  nan  nan ...  nan  nan  nan]]

Indicii:
 [[  0   0]
 [  0   1]
 [  0   2]
 ...
 [177  11]
 [177  12]
 [177  13]]

Matricea noua:
 [[42.   42.   42.   ... 42.   42.   42.  ]
 [42.   42.   42.   ...  1.05 42.   42.  ]
 [ 1.   42.   42.   ... 42.    3.17 42.  ]
 ...
 [42.   42.   42.   ... 42.    1.56 42.  ]
 [42.   4

(1p) 9. Folosind functia `np.convolve`, sa se determine media alunecatoare (moving average) pentru un vector de 10000 de numere aleatoare; lungimea ferestrei alunecatore se da ca parametru al functiei construite de voi. Comparati rezultatele si viteza de executie cu a functiaie `naive_moving_average`.

Referinte:
1. [Moving average](https://en.wikipedia.org/wiki/Moving_average)
1. [np.convolve: How to Use Numpy convolve() Method](https://appdividend.com/2022/10/14/np-convolve/)

In [9]:
def moving_average_fast(x:np.ndarray, w:int)->np.ndarray:
    '''
    Calculează media alunecatoare folosind np.convolve cu mod 'valid'
    :param x(np.ndarray): array de numere
    :param w(int): lungimea ferestrei alunecatore
    Returneaza un array care reprezinta media alunecatoare
    '''
    assert x.ndim == 1, 'One dimension numpy array'
    assert w > 1, 'Average of at least two values'
    window = np.ones(w) / w    
    media = np.convolve(x, window, mode='valid')
    return media

def naive_moving_average(x, w): # de adnotat, docstring
    assert x.ndim == 1, 'One dimension numpy array'
    assert w > 1, 'Average of at least two values'
    result = np.zeros(x.shape[0]-w+1)
    for i in range(x.shape[0]-w+1):
        result[i] = np.mean(x[i:i+w])
    return result

len_vec, w = 10000, 10
x = np.random.rand(len_vec)

a = moving_average_fast(x, w)
b = naive_moving_average(x, w)

assert len(a) == len(b), 'The two methods should return vectors of the same lengths'
assert np.allclose(a, b), 'The two methods should return close vectors'

%timeit moving_average_fast(x, w)
%timeit naive_moving_average(x, w)

42.8 µs ± 2.49 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)
62.5 ms ± 4.07 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


(1p) 10. Se dau vectorii de valori $x=[x_0 \dots x_{n-1}]$, $t=[t_0, \dots t_{n-1}]$, cu $t[0] < t[1] < \dots$. Sa se calculeze intr-o functie, intr-o maniera vectorizata, vectorul $v$ ale carui componente sunt:
$$
v[i] = \frac{x[i+1] - x[i]}{t[i+1] - t[i]}
$$

In prealabil sa se verifice (vectorizat sau cu functii NumPy) ca vectorul $t$ este format doar din valori strict crescatoare. Comparati rezultatele si viteza de executie cu o implementare care construieste vectorul $v$ pas cu pas.

Furnizati si o implementare folosind [Numba](https://numba.pydata.org/numba-doc/latest/user/5minguide.html). 

In [10]:
def creare_vector(x:np.ndarray,t:np.ndarray)->np.ndarray:
    '''
    Verifica daca al doilea vector este ordonat crescator si 
    returneaza un vector a caror termeni sunt dati dupa formula
    v[i]=(x[i+1]-x[i])/(t[i+1]-t[i])
    :param x(np.ndarray): primul vector
    :param t(np.ndarray): al doilea vector
    '''
    sortat:bool=np.all(t[:-1]<t[1:])
    if sortat:
        return np.diff(x)/np.diff(t)
    else:
        print('Vectorul "t" nu e sortat!')
        return []
x = np.random.rand(1000)
t = np.random.rand(1000)
t.sort()

print(creare_vector(x,t))
%timeit creare_vector(x, t)
print(creare_vector.__doc__)

[-2.86205948e+02  7.52212073e+02 -5.07624482e+02  1.33692067e+02
 -1.47571720e+02  3.36031433e+01  5.21315626e+01 -7.06651166e+02
  1.94784019e+03 -1.23999507e+03  4.22031324e+02  1.90524204e+02
 -1.03750738e+01  4.61906568e+02 -2.04597420e+02  2.71941263e+02
 -6.76348308e+02 -4.99144625e+02  2.26087468e+04 -4.34617009e+03
  6.54820524e+03  1.02492809e+02 -8.35891005e+02 -2.69752943e+02
  1.04326419e+02  9.31233488e+02 -1.64014772e+02  3.87741836e+01
  3.70138542e+02  3.02068700e+02 -1.26143689e+03  7.71469120e+02
 -1.14425096e+05  9.89344542e+01 -7.75594515e+02 -3.69854098e+02
  5.52974903e+00 -8.40132872e+01  7.10158309e+02 -7.60683637e+02
  2.53263493e+02 -3.55216137e+02 -5.55636942e+02  8.27847700e+01
  4.86782711e+02 -7.33636645e+03  1.92357209e+03  8.45650302e+01
 -6.49463303e+02 -1.13956955e+03  2.55418766e+02 -2.43092715e+01
 -6.71376640e+01 -2.94742516e+02  3.40048369e+02  1.69106008e+02
 -4.74146705e+02 -2.24018124e+05  5.31458923e+00  2.23965630e+03
 -1.67416222e+02  8.95405

16.6 µs ± 695 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)

    Verifica daca al doilea vector este ordonat crescator si 
    returneaza un vector a caror termeni sunt dati dupa formula
    v[i]=(x[i+1]-x[i])/(t[i+1]-t[i])
    :param x(np.ndarray): primul vector
    :param t(np.ndarray): al doilea vector
    
